name: Deploy Bubu Agent

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python --version

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -e .
        pip install -e ".[dev]"

    - name: Run tests before deployment
      run: |
        source venv/bin/activate
        cp env.example .env
        # Set test values
        sed -i 's/GF_NAME=YourGirlfriendName/GF_NAME=TestGirlfriend/g' .env
        sed -i 's/GF_WHATSAPP_NUMBER=+1234567890/GF_WHATSAPP_NUMBER=+1234567890/g' .env
        sed -i 's/SENDER_WHATSAPP_NUMBER=+1234567890/SENDER_WHATSAPP_NUMBER=+1234567890/g' .env
        sed -i 's/HF_API_KEY=your_huggingface_api_key_here/HF_API_KEY=test_key/g' .env
        sed -i 's/API_BEARER_TOKEN=your_secure_bearer_token_here/API_BEARER_TOKEN=test_token/g' .env
        sed -i 's/TWILIO_ACCOUNT_SID=your_twilio_account_sid/TWILIO_ACCOUNT_SID=test_sid/g' .env
        sed -i 's/TWILIO_AUTH_TOKEN=your_twilio_auth_token/TWILIO_AUTH_TOKEN=test_token/g' .env
        sed -i 's/TWILIO_WHATSAPP_FROM=whatsapp:+1234567890/TWILIO_WHATSAPP_FROM=whatsapp:+1234567890/g' .env
        make test

    - name: Build Docker image
      run: |
        docker build -t bubu-agent:${{ github.ref_name }} .
        docker tag bubu-agent:${{ github.ref_name }} bubu-agent:latest

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  docker-push:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bubu-agent:${{ github.ref_name }} .
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/bubu-agent:${{ github.ref_name }} ${{ secrets.DOCKERHUB_USERNAME }}/bubu-agent:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/bubu-agent:${{ github.ref_name }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/bubu-agent:latest
